# Generated by Django 3.2.5 on 2021-12-14 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=350)),
                ('foto', models.ImageField(null=True, upload_to='imgTarjetas')),
                ('idtipotarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTarjetas.tipotarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_publciacion', models.DateField(auto_now=True)),
                ('idtarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTarjetas.tarjeta')),
                ('idusuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('idusuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tarjeta_lista', models.ManyToManyField(to='gestionTarjetas.Tarjeta')),
            ],
        ),
        migrations.CreateModel(
            name='Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=250)),
                ('idtarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTarjetas.tarjeta')),
                ('idusuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Califiacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('putucion', models.IntegerField()),
                ('idtarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionTarjetas.tarjeta')),
                ('idusuario', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
